CREATE TABLE stg_dataset1 (
    AppID INT,
    Name VARCHAR(255),
    Release_date DATE,
    Estimated_owners VARCHAR(50),
    Peak_CCU INT,
    Required_age INT,
    Price DECIMAL(10,2),
    Discount DECIMAL(5,2),
    DLC_count INT,
    About_the_game TEXT,
    Supported_languages TEXT,
    Full_audio_languages TEXT,
    Reviews TEXT,
    Header_image TEXT,
    Website TEXT,
    Support_url TEXT,
    Support_email VARCHAR(255),
    Windows BOOLEAN,
    Mac BOOLEAN,
    Linux BOOLEAN,
    Metacritic_score INT,
    Metacritic_url TEXT,
    User_score FLOAT,
    Positive INT,
    Negative INT,
    Score_rank INT,
    Achievements INT,
    Recommendations INT,
    Notes TEXT,
    Average_playtime_forever INT,
    Average_playtime_2weeks INT,
    Median_playtime_forever INT,
    Median_playtime_2weeks INT,
    Developers VARCHAR(255),
    Publishers VARCHAR(255),
    Categories TEXT,
    Genres TEXT,
    Tags TEXT,
    Screenshots TEXT,
    Movies TEXT
);

CREATE TABLE stg_dataset2_games (
    app_id INT,
    name VARCHAR(255),
    release_date DATE,
    is_free BOOLEAN,
    price_overview TEXT,
    languages TEXT,
    type VARCHAR(50)
);

CREATE TABLE stg_dataset2_reviews (
    app_id INT,
    review_score INT,
    review_score_description VARCHAR(255),
    positive INT,
    negative INT,
    total INT,
    metacritic_score INT,
    reviews TEXT,
    recommendations INT,
    steamspy_user_score FLOAT,
    steamspy_score_rank INT,
    steamspy_positive INT,
    steamspy_negative INT
);

CREATE TABLE stg_dataset2_steamspy (
    app_id INT,
    developer VARCHAR(255),
    publisher VARCHAR(255),
    owners_range VARCHAR(50),
    concurrent_users_yesterday INT,
    playtime_average_forever INT,
    playtime_average_2weeks INT,
    playtime_median_forever INT,
    playtime_median_2weeks INT,
    price DECIMAL(10,2),
    initial_price DECIMAL(10,2),
    discount DECIMAL(10,2),
    languages TEXT,
    genres TEXT
);

