CREATE TABLE raw_games (
    AppID INT PRIMARY KEY,
    Name VARCHAR(512),
    Release_date DATE,
    Estimated_owners VARCHAR(50),
    Peak_CCU INT,
    Required_age INT,
    Price DECIMAL(10,2),
    Discount DECIMAL(5,2),
    DLC_count INT,
    Header_image TEXT,
    Windows BOOLEAN,
    Mac BOOLEAN,
    Linux BOOLEAN,
    Metacritic_score INT,
    User_score FLOAT,
    Positive INT,
    Negative INT,
    Achievements INT,
    Recommendations INT,
    Median_playtime_forever INT,
    Categories TEXT,
    Genres TEXT,
    Tags TEXT,
    steamspy_positive INT,
    steamspy_negative INT,
    Estimated_Revenue INT
);